### PR TITLE
Add contentDescription to all relevant components

### LINKED ISSUE #175: Accessibility: many things read as "todo" with talkback
V0.0.15
Android 11

The menu items read as 
- "todo subscribed"
- "todo local"
- "todo all"
- "todo saved"
- "todo profile"
- todo inbox"

The tabs along the bottom read as "todo"
The upvote, downvote, star, and 3 dot menu read as "todo"

Edit: the buttons on the top right such as sort order and the three dot menu also do this

### PR DESCRIPTION
**Pull request by pipe01**
Hopefully I didn't miss anything. There are still some components with `contentDescription = null` because they don't represent anything by themselves and/or don't have any actions, for example the icons in settings menu items.

Fixes #175.

### CODE REVIEW

**Comment by dessalines** [comment]
This will have to come after https://github.com/dessalines/jerboa/pull/447 so you'll probably have to merge from therei

**Comment by pipe01** [comment]
There are some conflicts where #447 adds a specific key and I have added a more generic one (e.g. `create_report_back` vs `goBack`), which should I keep?

Also for @shortwavesurfer2009's comment, I'm not sure which way would be best so it's up to @dessalines.

**Comment by pipe01** [comment]
> the personProfile_viewAvatar and personProfile_viewBanner should likely say " Avatar image" and "Banner image" unless i am misunderstanding and they are buttons

They open up the image in the image viewer when pressed, so they kinda are buttons.

**Comment by dessalines** [comment]
`goBack` is probably fine.

> They open up the image in the image viewer when pressed, so they kinda are buttons.

I'm good either way, I don't know if there's a convention for image buttons, but the word button seems fine.

I imagine most of the strings already exist in strings.xml, so only create new ones if its really necessary. I  leave the rest up to you.

**Comment by pipe01** [comment]
Should be good now.

**Review by dessalines — COMMENTED** [review]
Found a few more:

- AppBars L75
- DrawerItem: 59
- Several in the pictrsimage file.
- A bunch that were set to null

Do a `Find in Files` and search for `contentDescription` to get the rest of them.

**Comment by pipe01** [comment]
Most of them are set to null on purpose, I'm thinking of adding some constant that's set to null to indicate that it's unnecessary.

**Review by dessalines — APPROVED** [review]

**Review by twizmwazin — APPROVED** [review]

**Comment by pipe01** [comment]
Is there anything blocking this?

**Comment by twizmwazin** [comment]
@pipe01 If you can fix the merge conflicts I'll merge it right away

**Comment by pipe01** [comment]
Done

**Pull request merged**
