### PR TITLE
Adding distinct Full Score, and ScoreAndDownvote vote display modes.

### PR DESCRIPTION
**Pull request by dessalines**
- Also making ScoreAndUpvotePercentage the new default, until these
  get added in the back-end.
- Context https://github.com/dessalines/jerboa/issues/1400

New FullScore mode:

Screenshot_2024-02-24-18-57-12-202-edit_com jerboa debug

### CODE REVIEW

**Comment by MV-GH** [comment]
I wouldn't turn `Full` into that, this is just a much visual clutter as before with the arrows. I would just keep `Full` as original arrows design

**Comment by dessalines** [comment]
I don't *really* want to move the score numbers back into the the footer bars, as that's showing the score in three places again. Totally agree that this is cluttered, but some ppl might want all that info. It also only shows for <90% approval.

**Comment by MV-GH** [comment]
> I don't really want to move the score numbers back into the the footer bars, 

What is your rational for this? Code complexity? UX: that is more visually cluttered? Blocks future design changes to the footer?

My rational for the old design, just boils down to that users don't like change to something they are used to. And the fact we can still easily achieve the previous design without much complexity

> as that's showing the score in three places again. 

Whats the third place? Footer, header

**Comment by dessalines** [comment]
Score-related data in 2 distinct spots, besides just one. No other lemmy app does this either.

We also shouldn't be hesitant also to change things just because people get used to the old way. Front end is always like that, ppl are resistant to even the tiniest change, regardless of how much better it is. We will never be able to make anything look better if we use inertia as our benchmark. 

The complexity also goes up now that we have these  modes, IMO we should just keep them in one spot, otherwise it gets a lot of questions like: Should the percent be in the footer, or the header? Should score+downvotes be in both the header and the footer?

**Comment by dessalines** [comment]
I'm also open to other places, or ways to group the score info. One thing I like about jerboa that I don't see other apps doing tho, is that both posts and comments have **score + time** in the top right. Other apps seem to only do that for comments, and treat posts differently.

**Comment by dessalines** [comment]
This is going to get entirely reworked in the back end into a larger set of bools: https://github.com/LemmyNet/lemmy/pull/4450

But I think this is still okay to merge, since the main thing this adds is a switch to score + upvote-pct as default, at least until the next release.

**Review by MV-GH — APPROVED** [review]

**Pull request merged**
