### PR TITLE
Dirty Fix for #1222

### PR DESCRIPTION
**Pull request by 0xFOSSMan**
Given my limited experience with Kotlin this maybe complete nonsense but I'll try it anyway

### CODE REVIEW

**Comment by 0xFOSSMan** [comment]
oh damn i didn't want to put it here, does that break anything with me themeing?

**Comment by MV-GH** [comment]
Not there, look in siteviewmodel where it sets unreadcount when the account changes in the init. There we check if ur not anon and set unread count. Change it so if ur anon that it sets it to 0

**Review by MV-GH — CHANGES_REQUESTED** [review]
see above

**Comment by 0xFOSSMan** [comment]
i'll set this fork up again to split that up. thx for the tip

**Pull request closed without merging**
