### PR TITLE
Replace gson.tojson with Parcelable implementation

### LINKED ISSUE #1061: Update takeDepsFromRoot, to use Parcelable
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

see context https://github.com/dessalines/jerboa/pull/1044#issuecomment-1638448740

### PR DESCRIPTION
**Pull request by MV-GH**
I also replaced the consume.Return & addReturn.
I tried to get `takeDepsFromRoot` to be one function but that did not work

@nahwneeth what do you think? 

Fixes #1061

### CODE REVIEW

**Review by dessalines — APPROVED** [review]

**Review by dessalines — CHANGES_REQUESTED** [review]
NM just tested, this crashes for some reason.

**Comment by MV-GH** [comment]
Do you still have the stack trace?

**Comment by MV-GH** [comment]
Cuz I cant reproduce this error, what action did you do?

**Review by dessalines — APPROVED** [review]
My bad. I just tried this after merging from main again, and couldn't replicate the error. It was crashing on startup. Anyways we can merge this after it passes CI, we'll pretty quickly know if it happens again.

**Comment by MV-GH** [comment]
These code changes shouldn't even trigger on startup. Probably was a room error

**Pull request merged**
