### PR TITLE
Revamped BottomBar to match MD3

### PR DESCRIPTION
**Pull request by ironveil**
Hi.
I have added more to the navigation bar to make it fit in with Material 3. This includes changing it from BottomAppBar to NavigationBar, and adding labels to each element.
I have also renamed community lists to search as it doesn't fit on a label, and search seems more appropriate.
Thanks, IV.

### CODE REVIEW

**Comment by kuroi-usagi** [comment]
Run` ./gradlew formatKotlin` to fix the fomatting issues

**Comment by ironveil** [comment]
> Run` ./gradlew formatKotlin` to fix the fomatting issues

Done, should all be fine now

**Comment by dessalines** [comment]
Still failing lint, run format again.

**Comment by ironveil** [comment]
Done, also moved the labels to stringResources so that they can be localised.

**Pull request merged**
