### PR TITLE
Replace all relevant dialogs with Animated Center Popup menus

### LINKED ISSUE #1065: Replace all relevant dialogs with M3 menus (Such as Sort/More options/post more options)
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Replace all relevant dialogs with M3 menus (Such as Sort/More options/post more options)

See https://m3.material.io/components/menus/guidelines#834fd8ef-b704-420d-8bf6-f2d21e19d2cc

Also add sub menus. especially for the more options on a post, should add one for Copy (4 copy things), Block (Block user/community), Report (Report / Write full Report) , Share (Link / image / post)

This will also fix bottom padding and should imo be more more cleaner and elegant design.

@dessalines @twizmwazin Do you agree with this?

### PR DESCRIPTION
**Pull request by MV-GH**
- Replace More options dialog in home/community
- Replace sort dialog home/community/post
- Replace post more options
- Replace comment more options
- Replace CommentReply/CommentReply options

https://github.com/dessalines/jerboa/assets/67873169/7f343ff2-cf00-4cee-bd8f-1def2ff01d5d

Fixes #1065

### CODE REVIEW

**Comment by MV-GH** [comment]
I fixed the original color issue, still waiting for upstream to include the fixes. In the mean time I am attempting to create a centered menu with animations but it is jittery

**Comment by dessalines** [comment]
This looks like a ton of custom code for something that google should have implemented in a simple way. Might even be worth checking out if someone's made a compose plugin for it.

**Comment by MV-GH** [comment]
Starting to look good

https://github.com/dessalines/jerboa/assets/67873169/7c21db64-5829-489f-9a2b-1da0368dfae5

**Comment by MV-GH** [comment]
I am not sure if upstream would want these changes. I'll make a issue to inquire about it.

The pr is ready btw

**Review by twizmwazin — APPROVED** [review]
This looks really good!

**Review by dessalines — APPROVED** [review]
In that case I'll approve, but if you can always try to upstream additions to these libraries first, so that other projects can take advantage of the customizations. If we find it useful, other people likely would too.

**Pull request merged**
