### PR TITLE
Use listing type use M3 dropdown instead of dialog

### PR DESCRIPTION
**Pull request by MV-GH**
part of #1065

https://github.com/dessalines/jerboa/assets/67873169/c3bf7b1b-f300-43d8-8006-2f667b2d9513

### CODE REVIEW

**Comment by MV-GH** [comment]
for sortTypes it needs to centrally put them like it does now with dialogs

**Review by dessalines — COMMENTED** [review]
Same with this one, could you post before / after pics?

**Comment by MV-GH** [comment]
There is a video, and the other looks the same as this but with different menu items

**Comment by dessalines** [comment]
Oops my bad. Looks great.

**Review by dessalines — APPROVED** [review]

**Pull request merged**
