### PR TITLE
Add switch to anonymous option

### PR DESCRIPTION
**Pull request by MV-GH**
Small QoL, many times I wanna test something in anon but I dont want to remove my currently logged in account. This will solve that.

https://github.com/dessalines/jerboa/assets/67873169/b4858b5d-4eaf-4cbe-b2fe-f54a763017c5

### CODE REVIEW

**Review by twizmwazin — APPROVED** [review]
In the future it would also be nice to support anonymous on a user-entered instance.

**Comment by MV-GH** [comment]
For that it would probably be better  to be able to configure the default API instance

**Comment by twizmwazin** [comment]
Suppose someone prefers not to have an account but wants to read the local feed on a few different instances without logging in. I think it would make more sense to present it as an option in the account switcher than forcing the user to go and update the default instance each time.

**Comment by MV-GH** [comment]
So something like anon@lemmy.ml anon@beehaw.org? And where would we make such account? in create account?

**Comment by twizmwazin** [comment]
Yeah, probably something like "login" or "save as anonymous"

**Pull request merged**
