### PR TITLE
Added Italian localization

### PR DESCRIPTION
**Pull request by andreaippo**
Added Italian localization

### CODE REVIEW

**Review by twizmwazin — APPROVED** [review]

**Comment by MV-GH** [comment]
The pipeline fails at `   <string name="login_view_model_is_not_a_lemmy_instance">%1$s non è un'istanza Lemmy</string>`

Possibly due to the `'`

**Comment by andreaippo** [comment]
> The pipeline fails at ` <string name="login_view_model_is_not_a_lemmy_instance">%1$s non è un'istanza Lemmy</string>`
> 
> Possibly due to the `'`

Thanks. On it!

**Comment by andreaippo** [comment]
> Hi, actually we were already talking on [how to translate in Italian here](https://feddit.it/post/288638) (on Feddit.it, an italian Lemmy instance). Join us if you wish

Hey,
Just saw this, but now my PR got merged.

Not a big deal, I guess you guys can just open follow-up PRs for stuff you'd like to propose to change.

Before starting working on this I've searched for open PRs with Italian in the title and couldn't find any.
That's why in the future I would suggest to start by opening a PR in Draft status, it's much easier for anyone to find (and comment). 😉

**Comment by andscape-dev** [comment]
Hi @andreaippo, I've pushed updates to the translations in #591 as you suggested. My fault for not creating a draft beforehand while I was working on it. If you have time to review the changes it'd be awesome.

In the future, you're welcome to join us on Feddit.it to discuss Italian language-related changes before merging. :)

**Pull request merged**
