### PR TITLE
Change CommunityTopBar to use LargeTopAppBar from ExperimentalMaterial3Api

### PR DESCRIPTION
**Pull request by vijaykramesh**
Right now on the web UI (in mobile and desktop) a community icon optionally appears on the bottom left, while the banner is centered:

  

but meanwhile in jerboa the community icon is centered as well, which generally obscures the middle of the banner picture: 

I would propose changing the jerboa UI to match web mobile & desktop, and have the community icon optionally appear bottom left justified with the community banner centered.

Creating this MR to propose the idea and then let me see if I can get this building locally to actually see if it works.

### CODE REVIEW

**Comment by dessalines** [comment]
Rather than doing little changes like this, we really need to move the entire banner, and about sections, into a top, smart collapsing app bar. For both the profile and community pages. 

See #7

**Comment by vijaykramesh** [comment]
that makes sense to me, will continue to fool around with this to see what I can come up with.

**Comment by vijaykramesh** [comment]
Latest version:
Screenshot 2023-06-08 at 7 01 34 PM

Screenshot 2023-06-08 at 7 02 07 PM
Screenshot 2023-06-08 at 7 01 57 PM

**Comment by vijaykramesh** [comment]
and just for comparison, the current version - 
Screenshot 2023-06-08 at 7 23 44 PM
Screenshot 2023-06-08 at 7 23 39 PM

**Comment by vijaykramesh** [comment]
ok this is basically ready for community (but not yet done for profile)

@dessalines some outstanding questions I had - should the community title appear even when there is a banner? right now I have it showing banner or title (and then optional icon overlay on the bottom left of the banner).  and based on wholly unscientific looking around on lemmy I chose `LargeTopAppBar` to best accommodate larger banners.

added a few more previews to validate the subscribed status looks good, and also added `CommunityTopSectionTest` and modified the woodpecker yaml to run `- ./gradlew connectedAndroidTest test` - I'm not sure if this was wholly necessary, I didn't see these  actually running anywhere as a part of the pipeline (and an erroneous print makes the tests currently fail on `main`, so I don't think they are)

**Comment by vijaykramesh** [comment]
commented out the test step for now it isn't working in CI and as I mentioned above I've never done android dev so am not sure of best practices here. Locally it works in android studio or via `./gradlew connectedAndroidTest test` as long as I have android studio running... 🤷 

Screenshot 2023-06-08 at 9 17 48 PM

Screenshot 2023-06-08 at 9 17 05 PM

**Comment by vijaykramesh** [comment]
rather than continually rebasing remote main onto this I'll wait for a review from @dessalines and answers to my questions above - then can do one last update to latest so CI will pass again.

**Comment by dessalines** [comment]
> should the community title appear even when there is a banner? right now I have it showing banner or title (and then optional icon overlay on the bottom left of the banner). and based on wholly unscientific looking around on lemmy I chose LargeTopAppBar to best accommodate larger banners.

I see the standard in Boost for reddit is to have titles / extra info at the bottom: Screenshot_2023-06-09-14-46-18-187_com rubenmayayo reddit
 
Then, to collapse into a simple name and options bar (that also smart hides when scrolling): Screenshot_2023-06-09-14-46-33-387_com rubenmayayo reddit

> also I'd prefer to not add profile in this same MR but then take a pass at adding it, but is that OK with you or do you want a single MR with both implemented so it closes issue https://github.com/dessalines/jerboa/issues/7 ?

We might as well add both, but lets get one working correctly in the way that we'd like first. There's also a good chance a lot of your work in one could be externalized to composables.

I'm testing this now.

**Review by dessalines — COMMENTED** [review]
I couldn't test this, because I get a crash when going to any community:

Screenshot_2023-06-09-14-57-13-203_com iiordanov bVNC

**Comment by dessalines** [comment]
Any updates?

**Comment by vijaykramesh** [comment]
Sorry I've been out of the country, will close this out for the time being and aim to come back to it next month.

**Pull request closed without merging**
