### PR TITLE
Added comment sorting functionality

### PR DESCRIPTION
**Pull request by a1studmuffin**
Added comment sorting functionality. Fixes https://github.com/dessalines/jerboa/issues/147.

comments_sorting

### CODE REVIEW

**Review by dessalines — APPROVED** [review]
Stellar job on this. I'm really thankful you didn't try to code something up from scratch, as seems to almost always happen. You kept the coding styles and everything consistent with how the PostListings sorting works elsewhere.

**Review by twizmwazin — APPROVED** [review]

**Comment by twizmwazin** [comment]
The CI seems to fail to start on this one @dessalines

**Comment by dessalines** [comment]
@a1studmuffin run `./gradlew formatKotlin`

**Comment by a1studmuffin** [comment]
> @a1studmuffin run `./gradlew formatKotlin`

Done

**Comment by kuroi-usagi** [comment]
@a1studmuffin could you please resolve the conflicts? It is a highly appreciated feature and i would love to see this in the next release.

**Comment by a1studmuffin** [comment]
> @a1studmuffin could you please resolve the conflicts? It is a highly appreciated feature and i would love to see this in the next release.

Yep, will take a look tomorrow. 👍

**Comment by a1studmuffin** [comment]
@dessalines @twizmwazin Think this should be good to go now, merge conflicts addressed and building successfully.

**Pull request merged**
