### PR TITLE
Add zero-width space to person/community's shown name

### PR DESCRIPTION
**Pull request by Snow4DV**
Addresses issue #775 - last word of community's name is cut if instance's URL is too long. I added zero-width space so it would cut name of instance only if it doesn't fit.

### CODE REVIEW

**Comment by MV-GH** [comment]
image
This works

**Review by MV-GH — APPROVED** [review]

**Review by dessalines — COMMENTED** [review]
Not a fan of this hack. Seems like something should be done for the post listing title, not here.

**Comment by MV-GH** [comment]
Well there you could change the Overflow to show the dots instead of cutting it off if that change in behavior is wanted. But doing the above change there is much harder.

**Comment by Snow4DV** [comment]
I think you're right - it's better just to change overflow in CommunityName to "overflow = TextOverflow.Ellipsis". In that case it will be eaiser to distinguish local communities from remote ones if such thing happens

**Pull request closed without merging**
