### PR TITLE
Try removing meltwater cache.

### PR DESCRIPTION
**Pull request by dessalines**
There's a good chance this cache doesn't actually save any time.

### CODE REVIEW

**Comment by MV-GH** [comment]
Yeah it doesn't save much, the biggest time i saved was with caching the deps between steps with the .gradle env and preventing the build tools download

**Comment by dessalines** [comment]
Yeah, I verified it doesn't save much time at all. Mostly a waste.

**Comment by MV-GH** [comment]
Can you upgrade the android images see https://github.com/CircleCI-Public/cimg-android/issues/127

**Comment by dessalines** [comment]
Done.

**Pull request merged**
