### PR TITLE
voteToggle unused resource removed from string resources

### LINKED ISSUE #698: Drop `voteToggle` unused string resource
- [ ] Drop `voteToggle` unused string resource

_Originally posted by @scottmmjackson in https://github.com/dessalines/jerboa/pull/674#discussion_r1232236238_

### PR DESCRIPTION
**Pull request by scottmmjackson**
- `voteToggle` unused string resource removed from resources

Fixes #698

### CODE REVIEW

**Review by dessalines — APPROVED** [review]
👍

**Review by twizmwazin — APPROVED** [review]

**Comment by beatgammit** [comment]
Looks like woodpecker broke. Try getting it to trigger, e.g. by doing `git commit --amend && git push --force`. That should trigger a rebuild.

**Comment by Eskuero** [comment]
Seems like you missed some of them.
```
app/src/main/res/values-ja/strings.xml:268: Error: "voteToggle" is translated here but not found in default locale 
app/src/main/res/values-fr/strings.xml:279: Error: "voteToggle" is translated here but not found in default locale 
app/src/main/res/values-nl/strings.xml:291: Error: "voteToggle" is translated here but not found in default locale 
```
I will try to send a pull request tomorrow if nobody else does it.

**Comment by scottmmjackson** [comment]
@Eskuero those translations seem to have been added after the PR was opened. The entire `values-ja` tree was merged yesterday.

**Pull request merged**
