### PR TITLE
Account Settings: Use Alorma Compose Settings Components

### PR DESCRIPTION
**Pull request by sabieber**
As promised in #612 I tried to replace all custom component for which Alorma Compose Settings provide a counter part.

The following components don't seem to be present in the lib:
* text field
* text area
* image selector

Because of this I left the custom components for these intact.

### CODE REVIEW

**Review by dessalines — APPROVED** [review]
Thank you... this is sooo much better. Fix that one conflict then I can merge.

**Comment by sabieber** [comment]
@dessalines I am trying to merge main into the branch but I seem to be unable to login to the new main development state of the app as a NPE is thrown (perhaps because of commit https://github.com/dessalines/jerboa/commit/7d9c5a68c47f568d5a17f6630450e2bd267220ac)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.jerboa.datatypes.types.ListingType.ordinal()' on a null object reference
                                                                                                    	at com.jerboa.ui.components.login.LoginViewModel$login$1.invokeSuspend(LoginViewModel.kt:103)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	```

It seems we want to read the ordinal of a setting that is not yet set for a freshly logged in account.

**Comment by sabieber** [comment]
I think I properly merged the two changes but I would like to test it locally before the PR is merged :)

**Comment by dessalines** [comment]
mmmk no problem, ping me whenever you're ready to go.

**Comment by dessalines** [comment]
Use https://voyager.lemmy.ml , the current `main` branch has breaking API changes.

**Comment by sabieber** [comment]
@dessalines Thanks for the hint. With an account on that instance my changes to the account settings view seem to work with the new enums. Did set them to "Subscribed" and "TopToday", reopening the settings it stayed the same and restarting the app launched the screen to "Subscribed" and "TopToday"
So my local tests are succesfull.

**Comment by dessalines** [comment]
Perfect, thanks!

**Review by dessalines — APPROVED** [review]

**Comment by sabieber** [comment]
Thanks for merging 👍🏻

**Pull request merged**
