### PR TITLE
Improve Russian translations

### PR DESCRIPTION
**Pull request by mittwerk**

### CODE REVIEW

**Review by MV-GH — APPROVED** [review]
Thanks!

Those entries that you marked non translatable if they had some translations could you remove them?

**Comment by mittwerk** [comment]
Well, you can take them back, but I don't think it's necessary to translate it into any language.

**Comment by MV-GH** [comment]
I agree that's why I asked if they have already translations that you would remove them.

**Review by dessalines — CHANGES_REQUESTED** [review]
What's going on with all these formatting and dependency changes? Just update the translations only.

**Comment by MV-GH** [comment]
Make a separate PR for those build changes

**Review by dessalines — APPROVED** [review]
Sweet, thx

**Pull request merged**
