### PR TITLE
Enable swiping on comments to go back to posts

### LINKED ISSUE #431: Allow swiping back on comments to return to post view
Many 3rd party reddit apps (Sync, Relay, etc)  have the feature where you can swipe back on comments back to the main page. It would be a nice QoL improvement if Jerboa did the same.

### PR DESCRIPTION
**Pull request by CharlieGitDB**
The Reddit clients I have always used on Android were Slide, Sync, Infinity, all of these by default support swiping left to right on a Post to go backwards.  I have made code changes to make this possible on the comments to go back to the post view.

Closes #431

(Sorry for the laggy recording)
> [swipebacklemmypr.webm](https://github.com/dessalines/jerboa/assets/17328118/13ea83d0-c6c8-4d49-a336-63c06d64b472)

### CODE REVIEW

**Review by twizmwazin — CHANGES_REQUESTED** [review]
This is an improvement, but I have two thoughts:

1. This should be enabled by default, honestly I don't even know if it needs an option. Do other apps offer this option?
2. The animation for this when I tested it in the emulator seems to be fade-out/fade-in. Other apps have a finger tracking animation. That's what I imagined in #431. I'm not opposed to this since this is still an improvement, but I'd leave the original issue open until we can do a finger-tracking animation.

**Comment by CharlieGitDB** [comment]
> This should be enabled by default, honestly I don't even know if it needs an option. Do other apps offer this option?
Fair enough.  I wanted it to be less invasive as a first PR from me.  As you said though I don't think there is any app that has it as an option.  I will remove.

> The animation for this when I tested it in the emulator seems to be fade-out/fade-in. Other apps have a finger tracking animation. That's what I imagined in https://github.com/dessalines/jerboa/issues/431. I'm not opposed to this since this is still an improvement, but I'd leave the original issue open until we can do a finger-tracking animation.

I'll see if I can make this happen tonight. I have not done much modern Android dev at all, I am primarily a web dev so I may not have the skills for this, but ill take a crack at it.

**Comment by CharlieGitDB** [comment]
@twizmwazin Alright I have updated it to have finger tracking animation.  It would be nice to have the swipe background be the previous Activity & not be black, but I don't really know how I could make that happen.

> [swipetodismiss.webm](https://github.com/dessalines/jerboa/assets/17328118/6e9f7174-afb2-4d1a-a9e5-d172fd7f471a)

**Comment by twizmwazin** [comment]
Yeah, `MaterialTheme.colors.background` would be a better choice over black. Still would like to have it show the previous view underneath but that can be a separate issue since this is a good improvement as-is.

**Comment by CharlieGitDB** [comment]
Alright I updated it to use MaterialTheme.colors.background on swipe.

As for not having it be a solid color and be the HomeActivity I will probably need to add it to some app drawer or something?  I don't know yet I would need to spend more time on it.  Which I don't think I will get to for a couple days minimum.

**Comment by CharlieGitDB** [comment]
Themed swipe back
> [themedswipeback.webm](https://github.com/dessalines/jerboa/assets/17328118/adaa49d7-b9d6-4112-bf45-fa9c8c231985)

**Review by twizmwazin — APPROVED** [review]

**Pull request merged**
