### PR TITLE
#661 Toolbar color

### PR DESCRIPTION
**Pull request by Schoolkid1**
By adding an separate value for the toolbar backgroundcolour this should fix the toolbar colour on Google Pixel phones.

### CODE REVIEW

**Comment by MV-GH** [comment]
Your PR proposes a merge into the wrong branch.
image
You should have a branch on your fork with the changes, and then you create a pullrequest that merges that branch into the main branch of the upstream repository (this repository)
image

**Comment by Schoolkid1** [comment]
Are you on discord? I am using GitKraken and I am looking all over the internet and following the steps but I think I am still doing it wrong

**Comment by MV-GH** [comment]
You can find me on matrix. What step are you having trouble with?

A manually cli approach (creating a fork through GitHub does many things for you) :
- clone the repo: `git clone  https://github.com/dessalines/jerboa.git` then go into that directory
- Add your origin `git remote add origin https://github.com/Schoolkid1/yourFork.git` Make a empty github repo and it add it as a remote, This will be your fork
- Add the upstream repository (This repository) `git remote add upstream https://github.com/dessalines/jerboa.git`
-  Pull changes from the upstream into your branch `git pull upstream main`
- Make a branch for your changes, you can use main but that complicates things `git checkout -b mybranchname` you do the changes here
-  Push your changes to your fork `git push -u`
- -Go to the pullrequests on this repository, at the top it will show you to create a pull request, if not you will have to create a pull request and search manually for your branch

**Comment by Schoolkid1** [comment]
I think i finally managed.

https://github.com/dessalines/jerboa/pull/1170

**Comment by Schoolkid1** [comment]
In the new pull request i still get all checks have failed, can you help me out what is going wrong there?

**Comment by MV-GH** [comment]
Alright i am closing these old PRs

**Pull request closed without merging**
