### PR TITLE
Add save post button in List view mode

### LINKED ISSUE #712: Add option to save post from list view
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

**Describe the feature request below**
Please add an option to save posts from list view.

Edit: Maybe a "swipe to save" would be applicable here so the list view doesn't get cluttered.

This has been requested in https://lemmy.ca/post/702033

### PR DESCRIPTION
**Pull request by noloman**
Closes #712 

Screenshot_20230617_170439

### CODE REVIEW

**Comment by jacobbates** [comment]
Just adding my 2c that I think this suggested implementation overcrowds the UI for list view and makes interacting with the voting buttons harder.

How about having a long-hold menu option on the list item, or have long-hold reveal an action bar below the post in list view with more reasonably sized buttons? It would be nice to keep it consistent with the card views in that way, since currently list lacks the additional context menu for block, report, permalink. Save post could be grouped with these.

**Comment by dessalines** [comment]
I agree with @jacobbates , this doesn't look too good as is. Adding a long-press expand action bar, like exists for comments, would be a much better solution. Or if not, just clicking into it is better.

The whole point of the list view mode is that it should be very compact.

**Review by dessalines — COMMENTED** [review]
See comments above.

**Comment by noloman** [comment]
> I agree with @jacobbates , this doesn't look too good as is. Adding a long-press expand action bar, like exists for comments, would be a much better solution. Or if not, just clicking into it is better.
> 
> The whole point of the list view mode is that it should be very compact.

what do you mean with `clicking into it`?

**Comment by dessalines** [comment]
The list view mode doesn't show on the `PostActivity` page, which shows the full card. That card has options to bookmark.

**Comment by noloman** [comment]
> The list view mode doesn't show on the `PostActivity` page, which shows the full card. That card has options to bookmark.

What about putting the save button to the right of the comments icon?

**Comment by dessalines** [comment]
I'm not really a fan of that either. Long-hold to show the action bar is a better solution that keeps it compact.

**Pull request closed without merging**
